### ISSUE TITLE
Log the estimate code size error state as a string

### ISSUE THREAD

**Issue by singh264** [0xdaryl/housekeeping#12]
This change builds on top of https://github.com/eclipse-openj9/openj9/issues/8664. Currently, the estimate code size error state is logged as a number https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L3540

**Comment by fjeremic** [comment]
Closing this as it is tracked in eclipse-openj9/openj9#13168.
